global.useMonetGlobalObject = true // run browser style tests
require('../src/monet')

require('./matcher-helper')
require('./curry-spec')
require('./either-spec')
require('./free-spec')
require('./io-spec')
require('./list-spec')
require('./maybe-spec')
require('./monad-laws-spec')
require('./monad-transformer-spec')
require('./nel-spec')
require('./reader-spec')
require('./validation-spec')
